"""
Medical History service endpoints. Generated by Copilot
"""
from datetime import date
from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity

from ..manager.medical_history_manager import MedicalHistoryManager, VALID_STATUSES
from ..manager.member_manager import MemberManager
from ..utils import get_pagination_params, make_pagination, error

medical_history_bp = Blueprint("medical_history", __name__)
manager = MedicalHistoryManager()
member_mgr = MemberManager()


def _resolve_subject_member(user_id: int, subject_member_id):
    """Resolve and validate subject_member_id; returns (member_id, error_response) tuple."""
    if subject_member_id is not None:
        try:
            mid = int(subject_member_id)
        except (TypeError, ValueError):
            return None, (jsonify(error("400", "Invalid subject_member_id")), 400)
        m = member_mgr.get_member(user_id, mid)
        if not m or m.status != "active":
            return None, (jsonify(error("404", "Member not found")), 404)
        return mid, None
    # Default to Self member
    self_m = member_mgr.get_or_create_self_member(user_id)
    return self_m.id, None


def _parse_bool(value):
    """Parse boolean from JSON payload. Returns (bool, ok)."""
    if isinstance(value, bool):
        return value, True
    if isinstance(value, int) and value in (0, 1):
        return bool(value), True
    if isinstance(value, str) and value.lower() in ("true", "false", "1", "0"):
        return value.lower() in ("true", "1"), True
    return None, False


def _parse_date(value):
    """Parse YYYY-MM-DD date string. Returns (date, ok)."""
    if not value:
        return None, True
    if isinstance(value, date) and not isinstance(value, __import__("datetime").datetime):
        return value, True
    try:
        return date.fromisoformat(str(value).strip()), True
    except (ValueError, TypeError):
        return None, False


def _serialize(h) -> dict:
    return {
        "id": h.id,
        "member_id": h.member_id,
        "onset_date": h.onset_date.isoformat() if h.onset_date else None,
        "disease_name": h.disease_name,
        "disease_status": h.disease_status,
        "is_present": h.is_present,
        "is_taking_medication": h.is_taking_medication,
        "condition_note": h.condition_note,
        "note": h.note,
        "medication_name": h.medication_name,
        "medication_dosage": h.medication_dosage,
        "medication_frequency": h.medication_frequency,
        "diagnosed_hospital": h.diagnosed_hospital,
        "doctor_name": h.doctor_name,
        "information_source": h.information_source,
        "created_at": h.created_at.isoformat() + "Z" if h.created_at else None,
        "updated_at": h.updated_at.isoformat() + "Z" if h.updated_at else None,
    }


@medical_history_bp.route("", methods=["POST"])
@jwt_required()
def create_history():
    user_id = get_jwt_identity()
    data = request.get_json(force=True) or {}

    member_id, err = _resolve_subject_member(user_id, data.get("subject_member_id"))
    if err:
        return err

    errors = {}

    disease_name = (data.get("disease_name") or "").strip()
    if not disease_name:
        errors.setdefault("disease_name", []).append("required")
    elif len(disease_name) > 120:
        errors.setdefault("disease_name", []).append("max length 120")

    disease_status = (data.get("disease_status") or "").strip().upper()
    if not disease_status:
        errors.setdefault("disease_status", []).append("required")
    elif disease_status not in VALID_STATUSES:
        errors.setdefault("disease_status", []).append(
            f"must be one of: {', '.join(sorted(VALID_STATUSES))}"
        )

    is_present_raw = data.get("is_present")
    if is_present_raw is None:
        errors.setdefault("is_present", []).append("required")
        is_present = None
    else:
        is_present, ok = _parse_bool(is_present_raw)
        if not ok:
            errors.setdefault("is_present", []).append("must be boolean")
            is_present = None

    is_taking_raw = data.get("is_taking_medication")
    if is_taking_raw is None:
        errors.setdefault("is_taking_medication", []).append("required")
        is_taking_medication = None
    else:
        is_taking_medication, ok = _parse_bool(is_taking_raw)
        if not ok:
            errors.setdefault("is_taking_medication", []).append("must be boolean")
            is_taking_medication = None

    onset_date_raw = data.get("onset_date")
    onset_date, ok = _parse_date(onset_date_raw)
    if not ok:
        errors.setdefault("onset_date", []).append("must be YYYY-MM-DD format")
        onset_date = None

    if errors:
        return jsonify(error("400", "Validation error", details=errors)), 400

    h = manager.create(
        user_id=user_id,
        member_id=member_id,
        disease_name=disease_name,
        disease_status=disease_status,
        is_present=is_present,
        is_taking_medication=is_taking_medication,
        onset_date=onset_date,
        condition_note=data.get("condition_note") or None,
        note=data.get("note") or None,
        medication_name=data.get("medication_name") or None,
        medication_dosage=data.get("medication_dosage") or None,
        medication_frequency=data.get("medication_frequency") or None,
        diagnosed_hospital=data.get("diagnosed_hospital") or None,
        doctor_name=data.get("doctor_name") or None,
        information_source=data.get("information_source") or None,
    )
    return jsonify(_serialize(h)), 201


@medical_history_bp.route("", methods=["GET"])
@jwt_required()
def list_histories():
    user_id = get_jwt_identity()
    page, size = get_pagination_params()

    subject_member_id = request.args.get("subject_member_id")
    member_id = None
    if subject_member_id is not None:
        try:
            member_id = int(subject_member_id)
        except (TypeError, ValueError):
            return jsonify(error("400", "Invalid subject_member_id")), 400
        m = member_mgr.get_member(user_id, member_id)
        if not m:
            return jsonify(error("404", "Member not found")), 404

    disease_status = request.args.get("disease_status")
    if disease_status and disease_status.upper() not in VALID_STATUSES:
        return jsonify(error("400", "Invalid disease_status")), 400
    if disease_status:
        disease_status = disease_status.upper()

    is_present = None
    is_present_q = request.args.get("is_present")
    if is_present_q is not None:
        is_present, ok = _parse_bool(is_present_q)
        if not ok:
            return jsonify(error("400", "Invalid is_present")), 400

    is_taking = None
    is_taking_q = request.args.get("is_taking_medication")
    if is_taking_q is not None:
        is_taking, ok = _parse_bool(is_taking_q)
        if not ok:
            return jsonify(error("400", "Invalid is_taking_medication")), 400

    total, items = manager.list(
        user_id=user_id,
        page=page,
        size=size,
        member_id=member_id,
        disease_status=disease_status,
        is_present=is_present,
        is_taking_medication=is_taking,
    )
    return jsonify({
        "records": [_serialize(h) for h in items],
        "pagination": make_pagination(page, size, total),
    }), 200


@medical_history_bp.route("/<int:history_id>", methods=["GET"])
@jwt_required()
def get_history(history_id: int):
    user_id = get_jwt_identity()
    h = manager.get(user_id, history_id)
    if not h:
        return jsonify(error("404", "Medical history not found")), 404
    return jsonify(_serialize(h)), 200


@medical_history_bp.route("/<int:history_id>", methods=["PUT"])
@jwt_required()
def update_history(history_id: int):
    user_id = get_jwt_identity()
    h = manager.get(user_id, history_id)
    if not h:
        return jsonify(error("404", "Medical history not found")), 404

    data = request.get_json(force=True) or {}
    errors = {}
    updates = {}

    if "subject_member_id" in data:
        new_member_id, err = _resolve_subject_member(user_id, data["subject_member_id"])
        if err:
            return err
        updates["member_id"] = new_member_id

    if "disease_name" in data:
        val = (data["disease_name"] or "").strip()
        if not val:
            errors.setdefault("disease_name", []).append("required")
        elif len(val) > 120:
            errors.setdefault("disease_name", []).append("max length 120")
        else:
            updates["disease_name"] = val

    if "disease_status" in data:
        val = (data["disease_status"] or "").strip().upper()
        if val not in VALID_STATUSES:
            errors.setdefault("disease_status", []).append(
                f"must be one of: {', '.join(sorted(VALID_STATUSES))}"
            )
        else:
            updates["disease_status"] = val

    if "is_present" in data:
        val, ok = _parse_bool(data["is_present"])
        if not ok:
            errors.setdefault("is_present", []).append("must be boolean")
        else:
            updates["is_present"] = val

    if "is_taking_medication" in data:
        val, ok = _parse_bool(data["is_taking_medication"])
        if not ok:
            errors.setdefault("is_taking_medication", []).append("must be boolean")
        else:
            updates["is_taking_medication"] = val

    if "onset_date" in data:
        val, ok = _parse_date(data["onset_date"])
        if not ok:
            errors.setdefault("onset_date", []).append("must be YYYY-MM-DD format")
        else:
            updates["onset_date"] = val

    for opt_field in (
        "condition_note", "note", "medication_name", "medication_dosage",
        "medication_frequency", "diagnosed_hospital", "doctor_name", "information_source",
    ):
        if opt_field in data:
            updates[opt_field] = data[opt_field] or None

    if errors:
        return jsonify(error("400", "Validation error", details=errors)), 400

    h = manager.update(h, **updates)
    return jsonify(_serialize(h)), 200


@medical_history_bp.route("/<int:history_id>", methods=["DELETE"])
@jwt_required()
def delete_history(history_id: int):
    user_id = get_jwt_identity()
    h = manager.get(user_id, history_id)
    if not h:
        return jsonify(error("404", "Medical history not found")), 404
    manager.delete(h)
    return jsonify({"message": "Deleted"}), 200
