"""Health manager layer. Generated by Zhuang"""

import json
from datetime import datetime, timedelta
from typing import List, Optional, Tuple

from sqlalchemy import or_, select

from ..extensions import db
from ..models import HealthRecord, RecordSubject
from ..resilience.policy import db_breaker, with_retry


class DuplicateHealthRecordError(ValueError):
    """Raised when a member already has a record in the same minute."""


class HealthManager:
    @staticmethod
    def _normalize_to_minute(timestamp: datetime) -> datetime:
        # Stored timestamps are naive UTC (tzinfo=None). Normalize to minute precision.
        return timestamp.replace(second=0, microsecond=0)

    @db_breaker
    @with_retry()
    def create(
        self,
        user_id: int,
        systolic: int,
        diastolic: int,
        heart_rate: Optional[int],
        timestamp: datetime,
        tags: List[str],
        note: Optional[str],
        subject_member_id: int,
        treat_unmapped_as_self: bool = False,
    ) -> HealthRecord:
        normalized = self._normalize_to_minute(timestamp)
        minute_end = normalized + timedelta(minutes=1)

        # Duplicate check: same member cannot have more than one record in the same minute.
        # For legacy records that have no RecordSubject mapping yet, treat them as Self when requested.
        subq_member = select(RecordSubject.record_id).where(RecordSubject.member_id == subject_member_id)
        member_match = HealthRecord.id.in_(subq_member)
        if treat_unmapped_as_self:
            subq_any = select(RecordSubject.record_id)
            unmapped_match = ~HealthRecord.id.in_(subq_any)
            membership_clause = or_(member_match, unmapped_match)
        else:
            membership_clause = member_match

        exists = (
            db.session.query(HealthRecord.id)
            .filter(
                HealthRecord.user_id == user_id,
                HealthRecord.timestamp >= normalized,
                HealthRecord.timestamp < minute_end,
                membership_clause,
            )
            .first()
        )
        if exists is not None:
            raise DuplicateHealthRecordError("duplicate record for member in the same minute")

        rec = HealthRecord()
        rec.user_id = user_id
        rec.systolic = systolic
        rec.diastolic = diastolic
        rec.heart_rate = heart_rate
        rec.timestamp = normalized
        # Generated by Zhuang: preserve non-ASCII characters for exact contains on Chinese tags
        rec.tags = json.dumps(tags, ensure_ascii=False)
        rec.note = note
        db.session.add(rec)
        db.session.commit()
        return rec

    def _base_query(self, user_id: int):
        return HealthRecord.query.filter_by(user_id=user_id)

    @db_breaker
    def get(self, user_id: int, rec_id: int) -> Optional[HealthRecord]:
        return HealthRecord.query.filter_by(id=rec_id, user_id=user_id).first()

    @db_breaker
    def count(self, user_id: int, q):
        return q.count()

    @db_breaker
    def list(
        self,
        user_id: int,
        page: int,
        size: int,
        tags: Optional[List[str]],
        date_from: Optional[datetime],
        date_to: Optional[datetime],
        subject_member_id: Optional[int] = None,
    ) -> Tuple[int, List[HealthRecord]]:
        q = self._base_query(user_id)
        if subject_member_id is not None:
            subq = select(RecordSubject.record_id).where(RecordSubject.member_id == subject_member_id)
            q = q.filter(HealthRecord.id.in_(subq))
        if tags:
            # Generated by Zhuang: Use OR semantics and exact tag match; support both raw and \u-escaped storage
            # per_tag_condition = OR(contains('"餐后"'), contains('"\u9910\u540e"'))
            conditions = []
            for t in tags:
                raw = f'"{t}"'
                escaped = json.dumps(t, ensure_ascii=True)  # includes surrounding quotes
                conditions.append(or_(HealthRecord.tags.contains(raw), HealthRecord.tags.contains(escaped)))
            if conditions:
                q = q.filter(or_(*conditions))
        if date_from:
            q = q.filter(HealthRecord.timestamp >= date_from)
        if date_to:
            q = q.filter(HealthRecord.timestamp <= date_to)
        total = q.count()
        items = (
            q.order_by(HealthRecord.timestamp.desc())
            .offset((page - 1) * size)
            .limit(size)
            .all()
        )
        return total, items

    @db_breaker
    def list_all(
        self,
        user_id: int,
        tags: Optional[List[str]],
        date_from: Optional[datetime],
        date_to: Optional[datetime],
        subject_member_id: Optional[int] = None,
    ) -> List[HealthRecord]:
        """Return all records matching the filters without pagination. Generated by Zhuang"""
        q = self._base_query(user_id)
        if subject_member_id is not None:
            subq = select(RecordSubject.record_id).where(RecordSubject.member_id == subject_member_id)
            q = q.filter(HealthRecord.id.in_(subq))
        if tags:
            # Generated by Zhuang: OR semantics; support raw and escaped forms
            conditions = []
            for t in tags:
                raw = f'"{t}"'
                escaped = json.dumps(t, ensure_ascii=True)
                conditions.append(or_(HealthRecord.tags.contains(raw), HealthRecord.tags.contains(escaped)))
            if conditions:
                q = q.filter(or_(*conditions))
        if date_from:
            q = q.filter(HealthRecord.timestamp >= date_from)
        if date_to:
            q = q.filter(HealthRecord.timestamp <= date_to)
        return q.order_by(HealthRecord.timestamp.asc()).all()

    def check_duplicate_on_update(
        self,
        user_id: int,
        record_id: int,
        new_timestamp: datetime,
        subject_member_id: int,
    ) -> bool:
        """Check if updating to new_timestamp would create a duplicate. Returns True if duplicate found."""
        normalized = self._normalize_to_minute(new_timestamp)
        minute_end = normalized + timedelta(minutes=1)

        subq_member = select(RecordSubject.record_id).where(RecordSubject.member_id == subject_member_id)
        
        exists = (
            db.session.query(HealthRecord.id)
            .filter(
                HealthRecord.user_id == user_id,
                HealthRecord.id != record_id,  # Exclude current record
                HealthRecord.timestamp >= normalized,
                HealthRecord.timestamp < minute_end,
                HealthRecord.id.in_(subq_member),
            )
            .first()
        )
        return exists is not None

    @db_breaker
    @with_retry()
    def update(self, rec: HealthRecord, **fields) -> HealthRecord:
        for k, v in fields.items():
            if hasattr(rec, k):
                setattr(rec, k, v)
        db.session.commit()
        return rec

    @db_breaker
    @with_retry()
    def delete(self, rec: HealthRecord):
        db.session.delete(rec)
        db.session.commit()
        db.session.delete(rec)
        db.session.commit()
