"""
Medical History manager layer. Generated by Copilot
"""
from datetime import date
from typing import List, Optional, Tuple

from ..extensions import db
from ..models import MedicalHistory
from ..resilience.policy import db_breaker, with_retry

VALID_STATUSES = {"RECOVERED", "STABLE", "ONGOING", "RECURRENT", "PENDING_DIAGNOSIS"}


class MedicalHistoryManager:
    @db_breaker
    @with_retry()
    def create(
        self,
        user_id: int,
        member_id: int,
        disease_name: str,
        disease_status: str,
        is_present: bool,
        is_taking_medication: bool,
        onset_date: Optional[date] = None,
        condition_note: Optional[str] = None,
        note: Optional[str] = None,
        medication_name: Optional[str] = None,
        medication_dosage: Optional[str] = None,
        medication_frequency: Optional[str] = None,
        diagnosed_hospital: Optional[str] = None,
        doctor_name: Optional[str] = None,
        information_source: Optional[str] = None,
    ) -> MedicalHistory:
        h = MedicalHistory()
        h.user_id = user_id
        h.member_id = member_id
        h.onset_date = onset_date
        h.disease_name = disease_name
        h.disease_status = disease_status
        h.is_present = is_present
        h.is_taking_medication = is_taking_medication
        h.condition_note = condition_note
        h.note = note
        h.medication_name = medication_name
        h.medication_dosage = medication_dosage
        h.medication_frequency = medication_frequency
        h.diagnosed_hospital = diagnosed_hospital
        h.doctor_name = doctor_name
        h.information_source = information_source
        db.session.add(h)
        db.session.commit()
        return h

    @db_breaker
    def list(
        self,
        user_id: int,
        page: int,
        size: int,
        member_id: Optional[int] = None,
        disease_status: Optional[str] = None,
        is_present: Optional[bool] = None,
        is_taking_medication: Optional[bool] = None,
    ) -> Tuple[int, List[MedicalHistory]]:
        q = MedicalHistory.query.filter_by(user_id=user_id)
        if member_id is not None:
            q = q.filter_by(member_id=member_id)
        if disease_status:
            q = q.filter_by(disease_status=disease_status)
        if is_present is not None:
            q = q.filter_by(is_present=is_present)
        if is_taking_medication is not None:
            q = q.filter_by(is_taking_medication=is_taking_medication)
        total = q.count()
        items = (
            q.order_by(MedicalHistory.created_at.desc())
            .offset((page - 1) * size)
            .limit(size)
            .all()
        )
        return total, items

    @db_breaker
    def get(self, user_id: int, history_id: int) -> Optional[MedicalHistory]:
        return MedicalHistory.query.filter_by(id=history_id, user_id=user_id).first()

    @db_breaker
    @with_retry()
    def update(self, h: MedicalHistory, **fields) -> MedicalHistory:
        for k, v in fields.items():
            if hasattr(h, k):
                setattr(h, k, v)
        db.session.commit()
        return h

    @db_breaker
    @with_retry()
    def delete(self, h: MedicalHistory):
        db.session.delete(h)
        db.session.commit()
