#!/usr/bin/env node
// Generated by Zhuang
// Custom start script to fix React Scripts 5.0.1 dev server issues

const { spawn } = require('child_process');

// Set environment variables to fix dev server schema validation
process.env.GENERATE_SOURCEMAP = 'false';
process.env.BROWSER = 'none';
process.env.SKIP_PREFLIGHT_CHECK = 'true';
process.env.FAST_REFRESH = 'false';
process.env.WDS_SOCKET_HOST = 'localhost';
process.env.WDS_SOCKET_PORT = '3000';
process.env.WDS_SOCKET_PATH = '/ws';

// Start the development server
const child = spawn('npx', ['react-scripts', 'start'], {
  stdio: 'inherit',
  shell: true,
  env: {
    ...process.env,
    // Use allowedHosts from webpack.config.js instead of disabling host check
    PORT: '3000'
  }
});

child.on('error', (error) => {
  console.error('Error starting development server:', error);
  process.exit(1);
});

child.on('close', (code) => {
  console.log(`Development server exited with code ${code}`);
  process.exit(code);
});
