/**
 * Admin & Versioning E2E Flow - Standardized
 * Uses makeUser() for unique admin candidates
 * Generated by Copilot
 */
import { test, expect } from '@playwright/test';
import { makeUser } from '../utils/testData.js';
import { registerAndLoginWithTestId } from '../utils/auth.js';

// This test requires SUPER_ADMIN access and unique users, so disable shared auth
test.use({ storageState: undefined });

const DEFAULT_SA = { email: 'admin@example.com', password: 'ChangeMe123' };

test('super admin promotes admin and admin resets password', async ({ page }) => {
  // Create two unique users
  const adminCandidate = makeUser();
  const normalUser = makeUser();
  
  // Register both users
  await registerAndLoginWithTestId(page, adminCandidate);
  await page.evaluate(() => {
    localStorage.removeItem('access_token');
    localStorage.removeItem('refresh_token');
  });
  
  await registerAndLoginWithTestId(page, normalUser);
  await page.evaluate(() => {
    localStorage.removeItem('access_token');
    localStorage.removeItem('refresh_token');
  });

  // Try login as default SUPER_ADMIN
  await page.goto('/login');
  await page.getByTestId('login-email').fill(DEFAULT_SA.email);
  await page.getByTestId('login-password').fill(DEFAULT_SA.password);
  await page.getByTestId('login-submit').click();
  
  await page.waitForTimeout(1000);
  const isLogged = await page.getByTestId('current-user').isVisible().catch(() => false);
  if (!isLogged) {
    test.skip(true, 'Default SUPER_ADMIN not available; skipping admin flow test.');
  }

  // Navigate to Admin Users
  await page.goto('/admin/users');
  await expect(page.locator('text=Users')).toBeVisible({ timeout: 5000 }).catch(() => {});

  // Promote adminCandidate to ADMIN
  const adminRow = page.locator(`tr:has-text("${adminCandidate.email}")`);
  await expect(adminRow).toBeVisible();
  await adminRow.getByRole('button', { name: /Promote/i }).click();
  await page.waitForTimeout(500);

  // Logout by clearing tokens (UI text may vary by locale)
  await page.evaluate(() => {
    localStorage.removeItem('access_token');
    localStorage.removeItem('refresh_token');
  });

  // Login as new admin
  await uiLogin(page, adminCandidate.email, adminCandidate.password);
  await page.goto('/admin/users');

  // Reset normal user's password
  const userRow = page.locator(`tr:has-text("${normalUser.email}")`);
  await expect(userRow).toBeVisible();
  await userRow.getByRole('button', { name: /Reset Password/i }).click();
  await page.getByPlaceholder('New Password').fill('Newpass123');
  await page.getByRole('button', { name: /Confirm/i }).click();
  await page.waitForTimeout(500);

  // Logout and login as normal user with new password
  await page.evaluate(() => {
    localStorage.removeItem('access_token');
    localStorage.removeItem('refresh_token');
  });
  
  await page.goto('/login');
  await page.getByTestId('login-email').fill(normalUser.email);
  await page.getByTestId('login-password').fill('Newpass123');
  await page.getByTestId('login-submit').click();
  
  // Verify normal user can access dashboard
  await page.goto('/dashboard');
  await expect(page.getByTestId('current-user')).toContainText(normalUser.email);
});

