// Generated by Zhuang
import { test, expect } from '@playwright/test';
import { ensureChinese } from '../utils/auth';

const BASE_URL = process.env.E2E_BASE_URL || 'http://localhost:3000';
const API_URL = process.env.E2E_API_URL || 'http://localhost:5000';

async function registerAndLogin(page) {
  const email = `e2e_${Date.now()}@example.com`;
  await page.goto(`${BASE_URL}/register`);
  await page.getByPlaceholder('邮箱').fill(email);
  await page.getByPlaceholder('用户名').fill('e2e');
  await page.getByPlaceholder('密码').fill('Passw0rd!');
  await page.getByRole('button', { name: '注册' }).click();
  await page.waitForURL('**/login');
  // login
  await page.getByPlaceholder('邮箱').fill(email);
  await page.getByPlaceholder('密码').fill('Passw0rd!');
  await page.getByRole('button', { name: '登录' }).click();
  await page.waitForURL('**/dashboard');
  await ensureChinese(page);
}

async function openMembers(page) {
  await page.getByRole('menuitem', { name: '成员管理' }).click();
  await expect(page.getByRole('heading', { name: '成员管理' })).toBeVisible();
}

test('Self member is present and cannot be deleted', async ({ page }) => {
  await registerAndLogin(page);
  await openMembers(page);
  // find Self row
  const row = page.getByRole('row', { name: /Self/ });
  await expect(row).toBeVisible();
  // delete button should be disabled
  const delBtn = row.getByRole('button', { name: '删除' });
  await expect(delBtn).toBeDisabled();
});

