/**
 * Members Self Protection Test - Standardized
 * Uses shared authentication
 * Generated by Copilot
 */
import { test, expect } from '@playwright/test';
import { getSharedUser } from '../utils/session.js';
import { ensureChinese } from '../utils/auth.js';

test('Self member is present and cannot be deleted', async ({ page }) => {
  await page.goto('/');
  await ensureChinese(page);
  
  // Navigate to members page
  await page.getByRole('menuitem', { name: /成员管理|Members/i }).first().click();
  await expect(page.getByRole('heading', { name: /成员管理|Members/i })).toBeVisible();
  // find Self row
  const row = page.getByRole('row', { name: /Self/ });
  await expect(row).toBeVisible();
  // delete button should be disabled
  const delBtn = row.getByRole('button', { name: '删除' });
  await expect(delBtn).toBeDisabled();
});

