/**
 * E2E Regression Test: Complete User Journey (Chinese UI)
 * 
 * This test validates the core user journey from registration through
 * health record management and family member operations in Chinese UI.
 * 
 * Test Flow:
 * 1. Register new user (minute-stamped unique ID)
 * 2. Login with new user
 * 3. Ensure Chinese UI language
 * 4. Create valid health record for Self (default member)
 * 5. Attempt invalid out-of-range blood pressure (verify blocked)
 * 6. Edit existing record with new valid values (verify persistence)
 * 7. Create a family member (timestamped name)
 * 8. Switch to the new member
 * 9. Create health record for the new member (verify visible)
 * 
 * Generated by Copilot
 */

import { test, expect } from '@playwright/test';
import { registerAndLoginWithTestId, ensureChinese } from '../utils/auth.js';
import { makeUser, makeMemberName } from '../utils/testData.js';
import { createMember, switchMemberInHeader } from '../utils/members.js';

test.describe('E2E Regression: Complete User Journey (CN)', () => {
  
  test('should complete full user journey in Chinese UI', async ({ page }) => {
    // Generate unique test data with minute-level timestamp
    const testUser = makeUser();
    const memberName = makeMemberName(testUser.runId);
    
    console.log('=== Starting E2E Regression Test ===');
    console.log(`Test User: ${testUser.username}`);
    console.log(`Test Email: ${testUser.email}`);
    console.log(`Member Name: ${memberName}`);
    console.log(`Run ID: ${testUser.runId}`);
    
    // ===== Step 1 & 2: Register and Login =====
    console.log('\n--- Step 1-2: Register and Login ---');
    await registerAndLoginWithTestId(page, testUser);
    
    // Verify we're on dashboard/home and user is shown in header
    await expect(page.getByTestId('current-user')).toContainText(testUser.username);
    console.log('✓ User registered and logged in successfully');
    
    // ===== Step 3: Ensure Chinese UI (already done by registerAndLoginWithTestId) =====
    console.log('\n--- Step 3: Verify Chinese UI ---');
    // Verify Chinese marker is visible
    await expect(page.locator('text=健康记录')).toBeVisible();
    console.log('✓ Chinese UI confirmed');
    
    // ===== Step 4: Create valid health record for Self =====
    console.log('\n--- Step 4: Create Valid Health Record for Self ---');
    
    // Navigate to health records page
    await page.locator('text=/健康记录|Health Records/').click();
    await expect(page).toHaveURL(/\/health-records/);
    await expect(page.locator('h2:has-text("健康记录")')).toBeVisible();
    
    // Click Add Record button
    await page.getByRole('button', { name: /(添加|新增|增加|创建)记录|Add Record/i }).click();
    
    // Wait for modal to open
    await expect(page.locator('.ant-modal')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('text=/添加健康记录|新增健康记录|创建健康记录|Add Health Record/i').first()).toBeVisible();
    
    // Fill valid blood pressure (120/80)
    await page.locator('.ant-modal').locator('input[placeholder*="收缩压"]').fill('120');
    await page.locator('.ant-modal').locator('input[placeholder*="舒张压"]').fill('80');
    await page.locator('.ant-modal').locator('input[placeholder*="心率"]').fill('72');
    
    // Submit form
    const addBtn1 = page.locator('.ant-modal').locator('button[type="submit"]').filter({ hasText: /保\s?存|保存|Save/i });
    await expect(addBtn1.first()).toBeVisible({ timeout: 5000 });
    await addBtn1.first().click();
    
    // Verify success message
    await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
    
    // Wait for modal to close and table to refresh
    await expect(page.locator('.ant-modal')).not.toBeVisible({ timeout: 5000 });
    await page.waitForTimeout(1000);
    
    // Verify record appears in table with correct blood pressure
    await expect(page.locator('text=120/80')).toBeVisible();
    console.log('✓ Valid health record created for Self (120/80)');
    
    // ===== Step 5: Attempt invalid out-of-range blood pressure =====
    console.log('\n--- Step 5: Attempt Invalid Out-of-Range Blood Pressure ---');
    
    // Click Add Record again
    await page.getByRole('button', { name: /(添加|新增|增加|创建)记录|Add Record/i }).click();
    await expect(page.locator('.ant-modal')).toBeVisible({ timeout: 5000 });
    
    // Fill invalid blood pressure (300/30 - both out of range)
    await page.locator('.ant-modal').locator('input[placeholder*="收缩压"]').fill('300');
    await page.locator('.ant-modal').locator('input[placeholder*="舒张压"]').fill('30');
    
    // Try to submit
    const addBtn2 = page.locator('.ant-modal').locator('button[type="submit"]').filter({ hasText: /保\s?存|保存|Save/i });
    // when the form is invalid, the button should  still be visible but disabled, so we check for that
    await expect(addBtn2.first()).toBeVisible({ timeout: 5000 });
    await expect(addBtn2.first()).toBeDisabled();
    //await addBtn2.first().click();
    
    // Verify error state is visible (form validation error)
    await expect(page.locator('.ant-form-item-explain-error').first()).toBeVisible({ timeout: 5000 });
    
    // Verify modal is still open (submission was blocked)
    await expect(page.locator('.ant-modal')).toBeVisible();
    console.log('✓ Invalid blood pressure correctly blocked with error state');
    
    // Close the modal (click cancel or backdrop)
    await page.keyboard.press('Escape');
    await expect(page.locator('.ant-modal')).not.toBeVisible({ timeout: 5000 });
    
    // ===== Step 6: Edit existing record with new valid values =====
    console.log('\n--- Step 6: Edit Existing Record ---');
    
    // Find and click edit button for the first record (our 120/80 record)
    await page.getByRole('button', { name: /编辑|Edit/i }).first().click();
    
    // Wait for edit modal
    await expect(page.locator('.ant-modal')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('text=/编辑健康记录|修改健康记录|Edit Health Record/i').first()).toBeVisible();
    
    // Update blood pressure to 125/85
    const systolicInput = page.locator('.ant-modal').locator('input[placeholder*="收缩压"]');
    const diastolicInput = page.locator('.ant-modal').locator('input[placeholder*="舒张压"]');
    
    await systolicInput.clear();
    await systolicInput.fill('125');
    await diastolicInput.clear();
    await diastolicInput.fill('85');
    
    // Submit changes
    const updateBtn = page.locator('.ant-modal').locator('button[type="submit"]').filter({ hasText: /更\s?新|更新|Update/i });
    await expect(updateBtn.first()).toBeVisible({ timeout: 5000 });
    await updateBtn.first().click();
    
    // Verify success message
    await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
    
    // Wait for modal to close and table to refresh
    await expect(page.locator('.ant-modal')).not.toBeVisible({ timeout: 5000 });
    await page.waitForTimeout(1000);
    
    // Verify updated values appear in table
    await expect(page.locator('text=125/85')).toBeVisible();
    console.log('✓ Health record edited successfully (125/85)');
    
    // ===== Step 7: Create a family member =====
    console.log('\n--- Step 7: Create Family Member ---');
    
    await createMember(page, {
      full_name: memberName,
      gender: 'male',
      age: 35,
      weight: 75
    });
    
    console.log(`✓ Family member created: ${memberName}`);
    
    // ===== Step 8: Switch to the new member =====
    console.log('\n--- Step 8: Switch to New Member ---');
    
    await switchMemberInHeader(page, memberName);
    console.log(`✓ Switched to member: ${memberName}`);
    
    // ===== Step 9: Create health record for the new member =====
    console.log('\n--- Step 9: Create Health Record for New Member ---');
    
    // Navigate back to health records page
    await page.locator('text=/健康记录|Health Records/').click();
    await expect(page).toHaveURL(/\/health-records/);
    
    // Click Add Record button
    await page.getByRole('button', { name: /(添加|新增|增加|创建)记录|Add Record/i }).click();
    await expect(page.locator('.ant-modal')).toBeVisible({ timeout: 5000 });
    
    // Fill valid blood pressure for new member (130/85)
    await page.locator('.ant-modal').locator('input[placeholder*="收缩压"]').fill('130');
    await page.locator('.ant-modal').locator('input[placeholder*="舒张压"]').fill('85');
    await page.locator('.ant-modal').locator('input[placeholder*="心率"]').fill('75');
    
    // Submit form
    const addBtn3 = page.locator('.ant-modal').locator('button[type="submit"]').filter({ hasText: /保\s?存|保存|Save/i });
    await expect(addBtn3.first()).toBeVisible({ timeout: 5000 });
    await addBtn3.first().click();
    
    // Verify success message
    await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
    
    // Wait for modal to close and table to refresh
    await expect(page.locator('.ant-modal')).not.toBeVisible({ timeout: 5000 });
    await page.waitForTimeout(1000);
    
    // Verify record appears in table
    await expect(page.locator('text=130/85')).toBeVisible();
    console.log(`✓ Health record created for member: ${memberName} (130/85)`);
    // ===== Test Completed Successfully =====
    // output the user email and password for reference, so the tester can log in manually if needed
    console.log('\n=== Test Completed Successfully ===');
    console.log(`Test User Email: ${testUser.email}`);
    console.log(`Test User Password: ${testUser.password}`);
    console.log('\n=== E2E Regression Test Completed Successfully ===');
  });
  
});
