/**
 * Global Setup for E2E Tests
 * Creates a shared test user and saves authentication state for reuse
 * This runs once before all tests to avoid repeated registration/login
 * Generated by Copilot
 */

import { chromium } from '@playwright/test';
import { registerAndLoginWithTestId } from './utils/auth.js';
import { makeUser } from './utils/testData.js';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const STORAGE_STATE_PATH = path.join(__dirname, '.auth', 'user.json');
const SHARED_USER_PATH = path.join(__dirname, '.auth', 'shared-user.json');

export default async function globalSetup(config) {
  console.log('\n=== Global Setup: Creating Shared Test User ===');
  
  // Ensure .auth directory exists
  const authDir = path.dirname(STORAGE_STATE_PATH);
  if (!fs.existsSync(authDir)) {
    fs.mkdirSync(authDir, { recursive: true });
  }
  
  // Create a shared test user with deterministic runId for this test session
  const sessionId = `shared-${Date.now()}`;
  const sharedUser = makeUser(sessionId);
  
  console.log(`Shared Test User: ${sharedUser.email}`);
  console.log(`Password: ${sharedUser.password}`);
  
  // Launch browser and perform registration + login
  const browser = await chromium.launch();
  const context = await browser.newContext({
    baseURL: config.use?.baseURL || 'http://localhost:3000',
    locale: 'zh-CN',
    timezoneId: 'Asia/Shanghai',
  });
  
  const page = await context.newPage();
  
  try {
    // Register and login the shared user
    await registerAndLoginWithTestId(page, sharedUser, { skipLogout: true });
    
    // Save authentication state (cookies, localStorage, sessionStorage)
    await context.storageState({ path: STORAGE_STATE_PATH });
    console.log(`✓ Authentication state saved to: ${STORAGE_STATE_PATH}`);
    
    // Save shared user data for tests to reference
    fs.writeFileSync(SHARED_USER_PATH, JSON.stringify(sharedUser, null, 2));
    console.log(`✓ Shared user data saved to: ${SHARED_USER_PATH}`);
    
    console.log('=== Global Setup Complete ===\n');
  } catch (error) {
    console.error('❌ Global Setup Failed:', error);
    throw error;
  } finally {
    await context.close();
    await browser.close();
  }
}
