"""
Test cases for medical history endpoints. Generated by Copilot
"""
import pytest


def _register_and_login(client, email="user@test.com", password="pass1234"):
    client.post("/api/v1/auth/register", json={
        "username": "testuser",
        "email": email,
        "password": password,
        "age": 30,
        "gender": "male",
        "weight": 70,
    })
    resp = client.post("/api/v1/auth/login", json={"email": email, "password": password})
    token = resp.get_json()["access_token"]
    return {"Authorization": f"Bearer {token}"}


def _create_history(client, headers, **overrides):
    payload = {
        "disease_name": "Hypertension",
        "disease_status": "ONGOING",
        "is_present": True,
        "is_taking_medication": True,
    }
    payload.update(overrides)
    return client.post("/api/v1/medical-history", json=payload, headers=headers)


class TestMedicalHistoryCreate:
    def test_create_for_self(self, client, auth_headers):
        h = auth_headers["access"]
        resp = _create_history(client, h)
        assert resp.status_code == 201
        data = resp.get_json()
        assert data["disease_name"] == "Hypertension"
        assert data["disease_status"] == "ONGOING"
        assert data["is_present"] is True
        assert data["is_taking_medication"] is True
        assert "id" in data
        assert "member_id" in data

    def test_create_with_optional_fields(self, client, auth_headers):
        h = auth_headers["access"]
        resp = _create_history(
            client, h,
            onset_date="2024-01-15",
            condition_note="Under control with medication",
            medication_name="Amlodipine",
            medication_dosage="5mg",
            medication_frequency="Once daily",
            diagnosed_hospital="City Hospital",
            doctor_name="Dr. Smith",
            information_source="GP referral",
            note="Follow up in 3 months",
        )
        assert resp.status_code == 201
        data = resp.get_json()
        assert data["onset_date"] == "2024-01-15"
        assert data["medication_name"] == "Amlodipine"
        assert data["medication_dosage"] == "5mg"
        assert data["diagnosed_hospital"] == "City Hospital"

    def test_create_for_family_member(self, client, auth_headers):
        h = auth_headers["access"]
        member_resp = client.post("/api/v1/members", json={"full_name": "Alice"}, headers=h)
        assert member_resp.status_code == 201
        member_id = member_resp.get_json()["id"]

        resp = _create_history(client, h, subject_member_id=member_id)
        assert resp.status_code == 201
        data = resp.get_json()
        assert data["member_id"] == member_id

    def test_create_requires_disease_name(self, client, auth_headers):
        h = auth_headers["access"]
        resp = _create_history(client, h, disease_name="")
        assert resp.status_code == 400
        details = resp.get_json().get("details", {})
        assert "disease_name" in details

    def test_create_invalid_disease_status(self, client, auth_headers):
        h = auth_headers["access"]
        resp = _create_history(client, h, disease_status="INVALID_STATUS")
        assert resp.status_code == 400
        details = resp.get_json().get("details", {})
        assert "disease_status" in details

    def test_create_invalid_onset_date(self, client, auth_headers):
        h = auth_headers["access"]
        resp = _create_history(client, h, onset_date="not-a-date")
        assert resp.status_code == 400
        details = resp.get_json().get("details", {})
        assert "onset_date" in details

    def test_create_missing_required_booleans(self, client, auth_headers):
        h = auth_headers["access"]
        resp = client.post("/api/v1/medical-history", json={
            "disease_name": "Diabetes",
            "disease_status": "STABLE",
        }, headers=h)
        assert resp.status_code == 400
        details = resp.get_json().get("details", {})
        assert "is_present" in details
        assert "is_taking_medication" in details

    def test_create_invalid_member(self, client, auth_headers):
        h = auth_headers["access"]
        resp = _create_history(client, h, subject_member_id=99999)
        assert resp.status_code == 404

    def test_create_all_disease_statuses(self, client, auth_headers):
        h = auth_headers["access"]
        for status in ("RECOVERED", "STABLE", "ONGOING", "RECURRENT", "PENDING_DIAGNOSIS"):
            resp = _create_history(client, h, disease_status=status)
            assert resp.status_code == 201, f"Failed for status={status}"


class TestMedicalHistoryList:
    def test_list_returns_own_records(self, client, auth_headers):
        h = auth_headers["access"]
        _create_history(client, h, disease_name="Hypertension")
        _create_history(client, h, disease_name="Diabetes")
        resp = client.get("/api/v1/medical-history", headers=h)
        assert resp.status_code == 200
        data = resp.get_json()
        assert len(data["records"]) == 2
        assert "pagination" in data

    def test_list_pagination(self, client, auth_headers):
        h = auth_headers["access"]
        for i in range(5):
            _create_history(client, h, disease_name=f"Disease {i}")
        resp = client.get("/api/v1/medical-history?page=1&size=3", headers=h)
        assert resp.status_code == 200
        data = resp.get_json()
        assert len(data["records"]) == 3
        assert data["pagination"]["total"] == 5
        assert data["pagination"]["pages"] == 2

    def test_list_filter_by_member(self, client, auth_headers):
        h = auth_headers["access"]
        member_resp = client.post("/api/v1/members", json={"full_name": "Bob"}, headers=h)
        member_id = member_resp.get_json()["id"]

        _create_history(client, h, disease_name="Self Disease")
        _create_history(client, h, disease_name="Bob Disease", subject_member_id=member_id)

        resp = client.get(f"/api/v1/medical-history?subject_member_id={member_id}", headers=h)
        assert resp.status_code == 200
        data = resp.get_json()
        assert len(data["records"]) == 1
        assert data["records"][0]["disease_name"] == "Bob Disease"

    def test_list_filter_by_status(self, client, auth_headers):
        h = auth_headers["access"]
        _create_history(client, h, disease_status="RECOVERED")
        _create_history(client, h, disease_status="ONGOING")
        resp = client.get("/api/v1/medical-history?disease_status=RECOVERED", headers=h)
        assert resp.status_code == 200
        records = resp.get_json()["records"]
        assert all(r["disease_status"] == "RECOVERED" for r in records)


class TestMedicalHistoryGet:
    def test_get_own_record(self, client, auth_headers):
        h = auth_headers["access"]
        created = _create_history(client, h).get_json()
        resp = client.get(f"/api/v1/medical-history/{created['id']}", headers=h)
        assert resp.status_code == 200
        assert resp.get_json()["id"] == created["id"]

    def test_get_not_found(self, client, auth_headers):
        h = auth_headers["access"]
        resp = client.get("/api/v1/medical-history/99999", headers=h)
        assert resp.status_code == 404


class TestMedicalHistoryUpdate:
    def test_update_disease_name(self, client, auth_headers):
        h = auth_headers["access"]
        created = _create_history(client, h).get_json()
        resp = client.put(
            f"/api/v1/medical-history/{created['id']}",
            json={"disease_name": "Type 2 Diabetes"},
            headers=h,
        )
        assert resp.status_code == 200
        assert resp.get_json()["disease_name"] == "Type 2 Diabetes"

    def test_update_medication_fields(self, client, auth_headers):
        h = auth_headers["access"]
        created = _create_history(client, h).get_json()
        resp = client.put(
            f"/api/v1/medical-history/{created['id']}",
            json={"medication_name": "Metformin", "medication_dosage": "500mg"},
            headers=h,
        )
        assert resp.status_code == 200
        data = resp.get_json()
        assert data["medication_name"] == "Metformin"
        assert data["medication_dosage"] == "500mg"

    def test_update_invalid_status(self, client, auth_headers):
        h = auth_headers["access"]
        created = _create_history(client, h).get_json()
        resp = client.put(
            f"/api/v1/medical-history/{created['id']}",
            json={"disease_status": "BAD"},
            headers=h,
        )
        assert resp.status_code == 400

    def test_update_not_found(self, client, auth_headers):
        h = auth_headers["access"]
        resp = client.put("/api/v1/medical-history/99999", json={"disease_name": "X"}, headers=h)
        assert resp.status_code == 404


class TestMedicalHistoryDelete:
    def test_delete_own_record(self, client, auth_headers):
        h = auth_headers["access"]
        created = _create_history(client, h).get_json()
        resp = client.delete(f"/api/v1/medical-history/{created['id']}", headers=h)
        assert resp.status_code == 200
        # Verify it's gone
        get_resp = client.get(f"/api/v1/medical-history/{created['id']}", headers=h)
        assert get_resp.status_code == 404

    def test_delete_not_found(self, client, auth_headers):
        h = auth_headers["access"]
        resp = client.delete("/api/v1/medical-history/99999", headers=h)
        assert resp.status_code == 404


class TestMedicalHistoryCrossUserIsolation:
    def test_cannot_access_other_user_history(self, client):
        h1 = _register_and_login(client, "user1@test.com", "pass1234")
        h2 = _register_and_login(client, "user2@test.com", "pass1234")

        created = _create_history(client, h1).get_json()
        history_id = created["id"]

        # User 2 should not see it
        resp = client.get(f"/api/v1/medical-history/{history_id}", headers=h2)
        assert resp.status_code == 404

    def test_cannot_delete_other_user_history(self, client):
        h1 = _register_and_login(client, "del1@test.com", "pass1234")
        h2 = _register_and_login(client, "del2@test.com", "pass1234")

        created = _create_history(client, h1).get_json()
        history_id = created["id"]

        resp = client.delete(f"/api/v1/medical-history/{history_id}", headers=h2)
        assert resp.status_code == 404

    def test_list_only_returns_own_records(self, client):
        h1 = _register_and_login(client, "list1@test.com", "pass1234")
        h2 = _register_and_login(client, "list2@test.com", "pass1234")

        _create_history(client, h1, disease_name="User1 Disease")
        _create_history(client, h1, disease_name="User1 Disease 2")

        resp = client.get("/api/v1/medical-history", headers=h2)
        assert resp.status_code == 200
        assert resp.get_json()["pagination"]["total"] == 0
