/**
 * API Service for Health Platform
 * Generated by Zhuang
 */
import axios from 'axios';
import { MEMBER_SELECTION_KEY, MEMBER_SELECTION_OWNER_KEY } from '../utils/auth';

// Generated by Zhuang: resolve backend base URL
// - If REACT_APP_API_URL is provided, use it (works in any env)
// - In development without explicit env, use relative path '' so CRA dev-server proxies /api → http://localhost:5000 (avoids CORS on 192.168.x.x:3000)
// - In production, default to same-origin so Nginx can proxy /api
const BASE_URL = process.env.REACT_APP_API_URL || (process.env.NODE_ENV !== 'production' ? '' : '');

// Create axios instance
const api = axios.create({
  baseURL: BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request interceptor to add auth token
api.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('access_token');
    // Do not override explicit Authorization header (e.g., when sending refresh token)
    const hasExplicitAuth = config?.headers && Object.prototype.hasOwnProperty.call(config.headers, 'Authorization');
    if (token && !hasExplicitAuth) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// Response interceptor to handle token refresh
api.interceptors.response.use(
  (response) => {
    return response;
  },
  async (error) => {
    const originalRequest = error.config;

    if (error.response?.status === 401 && !originalRequest._retry) {
      originalRequest._retry = true;

      try {
        const refreshToken = localStorage.getItem('refresh_token');
        if (refreshToken) {
          // Use the same axios instance baseURL to avoid mismatch
          const response = await api.post(`/api/v1/auth/refresh`, {}, {
            headers: {
              Authorization: `Bearer ${refreshToken}`,
            },
          });

          const { access_token, refresh_token } = response.data;
          localStorage.setItem('access_token', access_token);
          localStorage.setItem('refresh_token', refresh_token);

          // Retry original request with new token
          originalRequest.headers.Authorization = `Bearer ${access_token}`;
          return api(originalRequest);
        }
      } catch (refreshError) {
        // Refresh failed, redirect to login
        localStorage.removeItem('access_token');
        localStorage.removeItem('refresh_token');
        localStorage.removeItem(MEMBER_SELECTION_KEY);
        localStorage.removeItem(MEMBER_SELECTION_OWNER_KEY);
        window.location.href = '/login';
        return Promise.reject(refreshError);
      }
    }

    return Promise.reject(error);
  }
);

// Auth APIs
export const authAPI = {
  register: (userData) => api.post('/api/v1/auth/register', userData),
  login: (credentials) => api.post('/api/v1/auth/login', credentials),
  refresh: () => api.post('/api/v1/auth/refresh'),
  // logout requires refresh token; allow passing custom config with headers
  logout: (config) => api.post('/api/v1/auth/logout', {}, config),
  logoutAll: () => api.post('/api/v1/auth/logout-all'),
  changePassword: (payload) => api.post('/api/v1/auth/change-password', payload),
};

// User APIs
export const userAPI = {
  getProfile: (userId) => api.get(`/api/v1/user/${userId}`),
  updateProfile: (userId, userData) => api.put(`/api/v1/user/${userId}`, userData),
};

// Health Record APIs
export const healthAPI = {
  createRecord: (recordData) => api.post('/api/v1/health', recordData),
  getRecords: (params) => api.get('/api/v1/health', { params }),
  getRecord: (recordId) => api.get(`/api/v1/health/${recordId}`),
  updateRecord: (recordId, recordData) => api.put(`/api/v1/health/${recordId}`, recordData),
  deleteRecord: (recordId) => api.delete(`/api/v1/health/${recordId}`),
  // Generated by Zhuang: Export CSV respecting filters and subject_member_id
  exportCsv: (params) => api.get('/api/v1/health/export', { params, responseType: 'blob' }),
  // Import APIs
  previewImport: (file, mapping) => {
    const formData = new FormData();
    formData.append('file', file);
    if (mapping) {
      formData.append('mapping', JSON.stringify(mapping));
    }
    // CRITICAL: Delete Content-Type to let browser auto-set multipart boundary
    return api.post('/api/v1/health/import/preview', formData, {
      headers: { 'Content-Type': undefined },
    });
  },
  commitImport: (sessionId, approvedMembers, memberMappings = {}) => api.post('/api/v1/health/import/commit', {
    session_id: sessionId,
    approved_new_members: approvedMembers,
    member_mappings: memberMappings,
  }),
  downloadImportTemplate: (format = 'excel') => api.get('/api/v1/health/import/template', {
    params: { format },
    responseType: 'blob',
  }),
  downloadImportReport: (payload) => api.post('/api/v1/health/import/report', payload, {
    responseType: 'blob',
  }),
};

// Members APIs (simplified family management)
export const memberAPI = {
  list: () => api.get('/api/v1/members'),
  create: (member) => api.post('/api/v1/members', member),
  update: (memberId, member) => api.put(`/api/v1/members/${memberId}`, member),
  remove: (memberId) => api.delete(`/api/v1/members/${memberId}`),
};

// Meta APIs
export const metaAPI = {
  getVersion: () => api.get('/api/v1/version'),
};

// Admin APIs
export const adminAPI = {
  listUsers: () => api.get('/api/v1/admin/users'),
  promoteAdmin: (userId) => api.post(`/api/v1/admin/users/${userId}/promote-admin`),
  demoteAdmin: (userId) => api.post(`/api/v1/admin/users/${userId}/demote-admin`),
  resetPassword: (userId) => api.post(`/api/v1/admin/users/${userId}/reset-password`, {}),
};

export default api;
