// Shared authentication utilities for E2E tests
// Generated by Copilot

import { expect } from '@playwright/test';

/**
 * Register a new user and login
 * @param {import('@playwright/test').Page} page
 */
export async function registerAndLogin(page) {
  const ts = Date.now();
  const user = {
    username: `e2e_user_${ts}`,
    email: `e2e.user.${ts}@example.com`,
    password: 'TestPassword123!'
  };

  console.log(`Registering test user: ${user.email}`);
  await page.goto('/register');
  
  // Fill registration form
  await page.fill('input[placeholder="请输入用户名"]', user.username);
  await page.fill('input[placeholder="请输入邮箱地址"]', user.email);
  await page.fill('input[placeholder="请输入密码"]', user.password);
  await page.fill('input[placeholder="请确认密码"]', user.password);
  
  // Handling optional fields if present or ignoring them if not critical for login
  const ageInput = page.locator('input[placeholder="年龄"]');
  if (await ageInput.isVisible()) {
    await ageInput.fill('28');
  }
  
  // Submit
  const regSubmit = page.locator('button[type="submit"]');
  await regSubmit.click();

  // Go to login
  await page.goto('/login');
  
  console.log(`Logging in with: ${user.email}`);
  await page.fill('input[placeholder="邮箱地址"]', user.email);
  await page.fill('input[placeholder="密码"]', user.password);
  
  const loginSubmit = page.locator('button[type="submit"]');
  await loginSubmit.click();
  
  // Wait for dashboard or any authenticated page
  await page.waitForTimeout(1000); // Wait for transition
  await expect(page).toHaveURL(/.*dashboard.*|.*health-records.*/);
  
  // Ensure Chinese language
  await ensureChinese(page);
}

/**
 * Ensure the application language is set to Chinese
 * @param {import('@playwright/test').Page} page
 */
export async function ensureChinese(page) {
  // Check if already in Chinese (look for "仪表板")
  try {
    const dashboardText = page.locator('text=仪表板').first();
    if (await dashboardText.isVisible({ timeout: 2000 })) {
      console.log('Language is already Chinese');
      return;
    }
  } catch (e) {
    // Ignore error
  }

  console.log('Language is likely English, switching to Chinese...');
  
  // Navigate to settings
  await page.goto('/settings');
  
  // Wait for settings page
  // English: "System Settings" or "Settings"
  // Chinese: "系统设置"
  await expect(page.locator('.ant-card-head-title')).toBeVisible();

  // Find the language select
  // It's the first select usually
  const select = page.locator('.ant-select').first();
  await select.click();
  
  // Select "中文" option (Ant design dropdown)
  // Options might be rendered in a portal (body)
  const option = page.locator('.ant-select-item-option-content:has-text("中文")').first();
  await option.click();
  
  // Click Save
  // English: "Save"
  // Chinese: "保存"
  const saveBtn = page.locator('button[type="submit"]');
  await saveBtn.click();
  
  // Wait for success toast
  await expect(page.locator('.ant-message-success')).toBeVisible();
  
  console.log('Language switched to Chinese successfully');
}
