// Shared authentication utilities for E2E tests
// Generated by Copilot

import { expect } from '@playwright/test';
import { makeUser } from './testData.js';

/**
 * Ensure user is logged out before running auth flow
 * @param {import('@playwright/test').Page} page
 */
async function ensureLoggedOut(page) {
  await page.goto('/');

  // Clear any client-side residue before interacting with UI
  try {
    await page.evaluate(() => {
      localStorage.clear();
      sessionStorage.clear();
    });
  } catch (e) {
    // Ignore if storage is not accessible yet
  }

  // If logout button is visible, click it to invalidate server session
  const logoutButton = page.getByRole('button', { name: /退出登录|Logout/i });
  if (await logoutButton.isVisible().catch(() => false)) {
    await logoutButton.click();
    await expect(page).toHaveURL(/\/login/);
  } else {
    // If already on login, we're done
    if (await page.url().includes('/login')) {
      return;
    }
    // Otherwise navigate to login page to ensure clean state
    await page.goto('/login');
  }
}

/**
 * Detect current UI language on the page
 * @param {import('@playwright/test').Page} page
 * @returns {Promise<'zh'|'en'>} Current language
 */
async function detectLanguage(page) {
  // Check for Chinese text markers
  try {
    const hasChineseMarker = await page.locator('text=创建您的健康账户').isVisible({ timeout: 1000 });
    if (hasChineseMarker) {
      console.log('Detected language: Chinese');
      return 'zh';
    }
  } catch (e) {
    // Not Chinese, continue checking
  }
  
  // Check for English text markers
  try {
    const hasEnglishMarker = await page.locator('text=Create Your Health Account').isVisible({ timeout: 1000 });
    if (hasEnglishMarker) {
      console.log('Detected language: English');
      return 'en';
    }
  } catch (e) {
    // Fallback
  }
  
  // Default to English if uncertain
  console.log('Could not detect language, defaulting to English');
  return 'en';
}

/**
 * Register a new user and login using stable data-testid selectors
 * Automatically adapts to current UI language (Chinese or English)
 * @param {import('@playwright/test').Page} page
 * @param {Object} [userData] - Optional user data; if not provided, generates new user
 * @returns {Promise<Object>} The created user data
 */
export async function registerAndLoginWithTestId(page, userData, options = {}) {
  const user = userData || makeUser();
  const { skipLogout = false } = options;

  // Avoid shared or residual login state unless explicitly skipped
  if (!skipLogout) {
    await ensureLoggedOut(page);
  }

  console.log(`Registering test user with testid selectors: ${user.email}`);
  await page.goto('/register');

  // Wait for page to load and registration form to appear
  await page.waitForLoadState('domcontentloaded');
  const registerUsername = page.getByTestId('register-username');
  const registerLink = page.getByRole('link', { name: /注册|Register/i });

  if (!(await registerUsername.isVisible({ timeout: 8000 }).catch(() => false))) {
    // If redirected to login or register not visible, try navigating via login page
    await page.goto('/login');
    if (await registerLink.isVisible({ timeout: 5000 }).catch(() => false)) {
      await registerLink.click();
    } else {
      // Directly retry register route
      await page.goto('/register');
    }
  }

  await expect(registerUsername).toBeVisible({ timeout: 20000 });
  
  // Detect current UI language
  const currentLang = await detectLanguage(page);
  console.log(`Registration will use ${currentLang === 'zh' ? 'Chinese' : 'English'} UI`);
  
  // Fill registration form using stable data-testid selectors
  await registerUsername.fill(user.username);
  await page.getByTestId('register-email').fill(user.email);
  await page.getByTestId('register-password').fill(user.password);
  await page.getByTestId('register-confirm').fill(user.password);
  await page.getByTestId('register-age').fill(String(user.age));
  
  // Gender is optional: try to pick one option once; skip entirely if not found
  const genderSelect = page.getByTestId('register-gender');
  if (await genderSelect.isVisible()) {
    try {
      await genderSelect.click();
      await page.waitForTimeout(200); // brief dropdown animation

      const genderText = currentLang === 'zh' ? '男' : 'Male';
      const dropdown = page.locator('.ant-select-dropdown [role="option"]').filter({ hasText: genderText }).first();

      if (await dropdown.isVisible({ timeout: 2000 })) {
        await dropdown.click();
        await page.keyboard.press('Escape'); // ensure dropdown closes, only one option chosen
      } else {
        console.log('Gender option not visible, skipping gender selection');
        await page.keyboard.press('Escape');
      }
    } catch (err) {
      console.log('Gender selection skipped due to error:', err.message);
      await page.keyboard.press('Escape');
    }
  }
  
  await page.getByTestId('register-weight').fill(String(user.weight));
  
  // Submit registration
  const regSubmit = page.getByTestId('register-submit');
  await expect(regSubmit).toBeVisible({ timeout: 10000 });
  await expect(regSubmit).toBeEnabled();
  await regSubmit.click();

  // Ensure we leave the register page (success or redirect)
  await expect(page).not.toHaveURL(/register/, { timeout: 12000 });
  
  // Wait for registration to complete (success toast or error)
  await Promise.race([
    page.waitForSelector('.ant-message-success', { timeout: 8000 }),
    page.waitForSelector('.ant-message-error', { timeout: 8000 }),
  ]).catch(() => {
    console.log('No toast appeared, proceeding to login');
  });

  // Navigate to login page
  await page.goto('/login');
  
  console.log(`Logging in with: ${user.email}`);
  await page.getByTestId('login-email').fill(user.email);
  await page.getByTestId('login-password').fill(user.password);
  
  const loginSubmit = page.getByTestId('login-submit');
  await expect(loginSubmit.first()).toBeVisible({ timeout: 10000 });
  await expect(loginSubmit.first()).toBeEnabled();
  await loginSubmit.first().click();

  // Wait for successful login (redirect to dashboard/home/settings) or error toast
  const loginError = page.locator('.ant-message-error');
  const loginSuccessUrl = (url) => {
    const pathname = url.pathname.replace(/\/+$/, '') || '/';
    return pathname === '/' || pathname.startsWith('/dashboard') || pathname.startsWith('/settings');
  };

  const loginOutcome = await Promise.race([
    page.waitForURL(loginSuccessUrl, { timeout: 12000 }).then(() => 'success'),
    loginError.waitFor({ timeout: 12000 }).then(() => 'error'),
  ]).catch(() => 'timeout');

  if (loginOutcome === 'error') {
    const errorText = (await loginError.first().innerText().catch(() => '')).trim();
    throw new Error(`Login failed: ${errorText || 'unknown error'}`);
  }

  if (loginOutcome === 'timeout') {
    throw new Error(`Login timed out, current URL: ${page.url()}`);
  }
  
  // Ensure Chinese language (as per requirement)
  await ensureChinese(page);
  
  // Verify header shows current user
  await expect(page.getByTestId('current-user')).toContainText(user.username);
  await expect(page.getByTestId('current-user')).toContainText(user.email);
  
  console.log(`User registered and logged in successfully: ${user.email}`);
  
  return user;
}

/**
 * Ensure the application language is set to Chinese (hardened for regression)
 * @param {import('@playwright/test').Page} page
 */
export async function ensureChinese(page) {
  console.log('Checking if language is already Chinese...');
  
  // Check if already in Chinese by looking for stable Chinese UI marker
  try {
    const chineseMarker = page.locator('text=健康记录').first();
    if (await chineseMarker.isVisible({ timeout: 2000 })) {
      console.log('Language is already Chinese - no change needed');
      return;
    }
  } catch (e) {
    // Language not Chinese or marker not found, proceed with switch
  }

  console.log('Language is not Chinese, switching to Chinese...');
  
  // Navigate to settings page
  await page.goto('/settings');

  // Frontend implementation reference:
  // Settings page renders a single Card with a Form.Item(label=t('settings.language')) containing an AntD Select.
  // There is ALSO a header MemberSelector (AntD Select) in Layout, so we must scope to the Settings form item.

  const languageFormItem = page
    .locator('.ant-form-item')
    .filter({ has: page.locator('.ant-form-item-label').getByText(/界面语言|Language/) })
    .first();
  await expect(languageFormItem).toBeVisible({ timeout: 10000 });

  const languageSelectRoot = languageFormItem.locator('.ant-select').first();
  await expect(languageSelectRoot).toBeVisible({ timeout: 10000 });

  // If already Chinese (selection shows 中文), skip.
  const currentSelection = languageSelectRoot.locator('.ant-select-selection-item').first();
  if (await currentSelection.isVisible()) {
    const currentText = (await currentSelection.innerText()).trim();
    if (/中文/.test(currentText)) {
      console.log('Language already set to Chinese via select value - no change needed');
      return;
    }
  }

  const selector = languageSelectRoot.locator('.ant-select-selector').first();
  const selectionItem = languageSelectRoot.locator('.ant-select-selection-item').first();
  const arrow = languageSelectRoot.locator('.ant-select-arrow').first();

  // Close any stray dropdowns (e.g., header MemberSelector) before we open the language select.
  try { await page.keyboard.press('Escape'); } catch {}
  try { await page.keyboard.press('Escape'); } catch {}

  const visibleDropdowns = page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden)');
  const chineseOption = visibleDropdowns.getByText(/中文（简体）|中文/, { exact: false }).first();
  const fallbackChineseOption = visibleDropdowns.locator('[role="option"]').filter({ hasText: /^zh$/i }).first();

  // Open dropdown (AntD Select can intercept clicks on the internal input; selection item / arrow is more reliable)
  let opened = false;
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      if (await selectionItem.isVisible({ timeout: 300 })) {
        await selectionItem.click();
      } else {
        await selector.click();
      }
    } catch {
      // ignore and try other strategies
    }

    try {
      await expect(visibleDropdowns.first()).toBeVisible({ timeout: 1000 });
    } catch {
      // Strategy 2: force click selector
      try { await selector.click({ force: true }); } catch {}
      try { await expect(visibleDropdowns.first()).toBeVisible({ timeout: 1000 }); } catch {}
    }

    // Strategy 3: keyboard open
    if (!(await visibleDropdowns.first().isVisible().catch(() => false))) {
      try { await selector.press('ArrowDown'); } catch {}
      try { await expect(visibleDropdowns.first()).toBeVisible({ timeout: 1000 }); } catch {}
    }

    // Strategy 4: click arrow icon
    if (!(await visibleDropdowns.first().isVisible().catch(() => false))) {
      try { await arrow.click({ force: true }); } catch {}
      try { await expect(visibleDropdowns.first()).toBeVisible({ timeout: 1000 }); } catch {}
    }

    if (await chineseOption.isVisible({ timeout: 500 }).catch(() => false) ||
        await fallbackChineseOption.isVisible({ timeout: 500 }).catch(() => false)) {
      opened = true;
      break;
    }

    // If a dropdown opened but it's not the language dropdown (no Chinese option), close and retry.
    try { await page.keyboard.press('Escape'); } catch {}
    await page.waitForTimeout(150);
  }

  if (!opened) {
    throw new Error('Failed to open language dropdown or locate Chinese option');
  }

  // Select Chinese option (label is "中文（简体）" in both zh/en locale files)
  const optionToClick = (await chineseOption.isVisible({ timeout: 1000 }).catch(() => false))
    ? chineseOption
    : fallbackChineseOption;
  await expect(optionToClick).toBeVisible({ timeout: 5000 });
  await optionToClick.click({ force: true });

  // Click Save (submit) button within the same Settings language form
  const languageForm = page.locator('form').filter({ has: languageFormItem }).first();
  const saveBtn = languageForm.locator('button[type="submit"]').first();
  await expect(saveBtn).toBeVisible({ timeout: 5000 });
  await saveBtn.click();
  
  // Wait for success toast
  await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
  
  // Wait a bit for language to actually switch in UI
  await page.waitForTimeout(1000);
  
  console.log('Language switched to Chinese successfully');
  
  // Verify Chinese UI marker is now visible
  const chineseMarkerVerify = page.locator('text=健康记录').first();
  await expect(chineseMarkerVerify).toBeVisible({ timeout: 5000 });
}
