/**
 * Member management helpers for E2E tests
 * Generated by Copilot
 */

import { expect } from '@playwright/test';

/**
 * Create a new family member
 * @param {import('@playwright/test').Page} page
 * @param {Object} memberData - Member data
 * @param {string} memberData.full_name - Member full name
 * @param {string} [memberData.gender] - Gender (male/female/other)
 * @param {number} [memberData.age] - Age
 * @param {number} [memberData.height] - Height in cm
 * @param {number} [memberData.weight] - Weight in kg
 * @returns {Promise<void>}
 */
export async function createMember(page, memberData) {
  console.log(`Creating member: ${memberData.full_name}`);
  
  // Navigate to members page (support i18n variations & non-link menuitems)
  const membersNav = page.getByRole('menuitem', { name: /成员管理|Members/ }).first();
  if (await membersNav.count()) {
    await membersNav.click();
  } else {
    // fallback: locate in sidebar by text
    await page.locator('aside').locator('text=/成员管理|Members/').first().click();
  }
  await expect(page).toHaveURL(/\/members/);

  // Wait for members page to load (choose level 2 to avoid strict violations)
  await expect(page.getByRole('heading', { level: 2, name: /成员管理|Members/ })).toBeVisible({ timeout: 10000 });

  // Click Add button (tolerate synonyms: 新增/增加/创建/添加/New)
  const addMemberBtn = page.getByRole('button', { name: /(\+\s*)?(新增|增加|创建|添加)成员|New Member|Add Member/i });
  await expect(addMemberBtn).toBeVisible({ timeout: 5000 });
  await addMemberBtn.click();

  // Wait for modal to open (title variants)
  await expect(page.locator('.ant-modal')).toBeVisible({ timeout: 5000 });
  await expect(page.locator('text=/创建成员|新增成员|增加成员|添加成员|New Member|Create Member/i').first()).toBeVisible();
  
  // Fill member form
  await page.locator('.ant-modal').locator('input[placeholder*="姓名"]').fill(memberData.full_name);
  
  if (memberData.gender) {
    // Open gender select
    await page.locator('.ant-modal').locator('.ant-select').click();
    await page.waitForTimeout(300);
    
    // Map gender to Chinese label
    const genderMap = {
      male: '男',
      female: '女',
      other: '其他'
    };
    const genderLabel = genderMap[memberData.gender] || '其他';
    await page.locator('.ant-select-dropdown').locator(`text=${genderLabel}`).click();
  }
  
  if (memberData.age) {
    await page.locator('.ant-modal').locator('input[placeholder*="年龄"]').fill(String(memberData.age));
  }
  
  if (memberData.height) {
    await page.locator('.ant-modal').locator('input[placeholder*="身高"]').fill(String(memberData.height));
  }
  
  if (memberData.weight) {
    await page.locator('.ant-modal').locator('input[placeholder*="体重"]').fill(String(memberData.weight));
  }
  
  // Submit form
  const saveBtn = page.locator('.ant-modal').getByRole('button', { name: /保\s*存|Save/ }).first();
  await expect(saveBtn).toBeVisible({ timeout: 5000 });
  await saveBtn.click();
  
  // Wait for success message
  await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
  
  // Wait for modal to close
  await expect(page.locator('.ant-modal')).not.toBeVisible({ timeout: 5000 });
  
  // Verify member appears in table
  await expect(page.locator(`text=${memberData.full_name}`)).toBeVisible();
  
  console.log(`Member created successfully: ${memberData.full_name}`);
}

/**
 * Switch to a specific member using the header member selector
 * @param {import('@playwright/test').Page} page
 * @param {string} memberDisplayName - The display name of the member (e.g., "自己" for Self, or member full name)
 * @returns {Promise<void>}
 */
export async function switchMemberInHeader(page, memberDisplayName) {
  console.log(`Switching to member: ${memberDisplayName}`);
  // refresh the page to ensure latest state
  await page.reload();
  
  
  // Find the member selector in header (it's the Select component before logout button)
  const memberSelector = page.locator('header').locator('.ant-select').first();
  
  // Click to open dropdown
  await expect(memberSelector).toBeVisible({ timeout: 5000 });
  await memberSelector.click();
  await page.waitForTimeout(300);
  
  // Select the member by display name
  const memberOption = page.locator('.ant-select-dropdown').locator(`.ant-select-item-option-content:has-text("${memberDisplayName}")`);
  await expect(memberOption).toBeVisible({ timeout: 5000 });
  await memberOption.click();
  
  // Wait a bit for the selection to take effect
  await page.waitForTimeout(500);
  
  console.log(`Switched to member: ${memberDisplayName}`);
}
