/**
 * Member management helpers for E2E tests
 * Generated by Copilot
 */

import { expect } from '@playwright/test';

/**
 * Create a new family member
 * @param {import('@playwright/test').Page} page
 * @param {Object} memberData - Member data
 * @param {string} memberData.full_name - Member full name
 * @param {string} [memberData.gender] - Gender (male/female/other)
 * @param {number} [memberData.age] - Age
 * @param {number} [memberData.height] - Height in cm
 * @param {number} [memberData.weight] - Weight in kg
 * @returns {Promise<void>}
 */
export async function createMember(page, memberData) {
  console.log(`Creating member: ${memberData.full_name}`);
  
  // Navigate to members page (support i18n variations & non-link menuitems)
  const membersNav = page.getByRole('menuitem', { name: /成员管理|Members/ }).first();
  if (await membersNav.count()) {
    await membersNav.click();
  } else {
    // fallback: locate in sidebar by text
    await page.locator('aside').locator('text=/成员管理|Members/').first().click();
  }
  await expect(page).toHaveURL(/\/members/);

  // Wait for members page to load (choose level 2 to avoid strict violations)
  await expect(page.getByRole('heading', { level: 2, name: /成员管理|Members/ })).toBeVisible({ timeout: 10000 });

  // Click Add button (tolerate synonyms: 新增/增加/创建/添加/New)
  const addMemberBtn = page.getByRole('button', { name: /(\+\s*)?(新增|增加|创建|添加)成员|New Member|Add Member/i });
  await expect(addMemberBtn).toBeVisible({ timeout: 5000 });
  await addMemberBtn.click();

  // Wait for modal to open (title variants)
  await expect(page.locator('.ant-modal')).toBeVisible({ timeout: 5000 });
  await expect(page.locator('text=/创建成员|新增成员|增加成员|添加成员|New Member|Create Member/i').first()).toBeVisible();
  
  // Fill member form
  await page.locator('.ant-modal').locator('input[placeholder*="姓名"]').fill(memberData.full_name);
  
  if (memberData.gender) {
    // Open gender select
    await page.locator('.ant-modal').locator('.ant-select').click();
    await page.waitForTimeout(300);
    
    // Map gender to Chinese label
    const genderMap = {
      male: '男',
      female: '女',
      other: '其他'
    };
    const genderLabel = genderMap[memberData.gender] || '其他';
    await page.locator('.ant-select-dropdown').locator(`text=${genderLabel}`).click();
  }
  
  if (memberData.age) {
    await page.locator('.ant-modal').locator('input[placeholder*="年龄"]').fill(String(memberData.age));
  }
  
  if (memberData.height) {
    await page.locator('.ant-modal').locator('input[placeholder*="身高"]').fill(String(memberData.height));
  }
  
  if (memberData.weight) {
    await page.locator('.ant-modal').locator('input[placeholder*="体重"]').fill(String(memberData.weight));
  }
  
  // Submit form
  const saveBtn = page.locator('.ant-modal').getByRole('button', { name: /保\s*存|Save/ }).first();
  await expect(saveBtn).toBeVisible({ timeout: 5000 });
  await saveBtn.click();
  
  // Wait for success message
  await expect(page.locator('.ant-message-success')).toBeVisible({ timeout: 5000 });
  
  // Wait for modal to close
  await expect(page.locator('.ant-modal')).not.toBeVisible({ timeout: 5000 });
  
  // Verify member appears in table
  await expect(page.locator(`text=${memberData.full_name}`)).toBeVisible();
  
  console.log(`Member created successfully: ${memberData.full_name}`);
}

/**
 * Switch to a specific member using the header member selector
 * @param {import('@playwright/test').Page} page
 * @param {string} memberDisplayName - The display name of the member (e.g., "自己" for Self, or member full name)
 * @returns {Promise<void>}
 */
export async function switchMemberInHeader(page, memberDisplayName) {
  console.log(`Switching to member: ${memberDisplayName}`);
  // refresh the page to ensure latest state
  await page.reload();

  // Deterministic switch: Settings are persisted via MemberContext to localStorage.
  // MemberContext keys:
  // - selected_member_id
  // - selected_member_owner (userId from JWT)
  // We resolve member id via authenticated fetch(/api/v1/members) in page context, set localStorage, then reload.
  const memberId = await page.evaluate(async (displayName) => {
    const token = localStorage.getItem('access_token');
    if (!token) return null;

    const decodeJwtSub = (jwt) => {
      try {
        const b64 = jwt.split('.')[1];
        if (!b64) return null;
        let base64 = b64.replace(/-/g, '+').replace(/_/g, '/');
        const pad = base64.length % 4;
        if (pad) base64 += '='.repeat(4 - pad);
        const json = atob(base64);
        const payload = JSON.parse(json);
        return payload.sub || payload.identity || null;
      } catch {
        return null;
      }
    };

    const userId = decodeJwtSub(token);
    if (!userId) return null;

    // Retry fetch a few times in case the new member isn't immediately visible.
    for (let i = 0; i < 5; i++) {
      const resp = await fetch('/api/v1/members', {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (resp.ok) {
        const data = await resp.json();
        const members = data.members || [];
        const target = members.find((m) => {
          const fullName = (m.full_name || '').trim();
          if (!fullName) return false;
          // UI may display Self as "自己" in zh; backend uses "Self".
          if (displayName === '自己' && fullName.toLowerCase() === 'self') return true;
          return fullName === displayName;
        });
        if (target && target.id != null) {
          localStorage.setItem('selected_member_id', String(target.id));
          localStorage.setItem('selected_member_owner', String(userId));
          return target.id;
        }
      }
      await new Promise((r) => setTimeout(r, 300));
    }
    return null;
  }, memberDisplayName);

  if (memberId == null) {
    // Fallback to UI dropdown selection if API-based resolution fails.
    console.warn(`Could not resolve member id for '${memberDisplayName}', falling back to UI select`);
    await expect(page.getByTestId('current-user')).toBeVisible({ timeout: 10000 });

    const header = page.locator('header').first();
    const memberSelectRoot = header.locator('.ant-select').first();
    await expect(memberSelectRoot).toBeVisible({ timeout: 10000 });
    const selector = memberSelectRoot.locator('.ant-select-selector').first();
    const selectionItem = memberSelectRoot.locator('.ant-select-selection-item').first();

    try { await page.keyboard.press('Escape'); } catch {}
    try {
      if (await selectionItem.isVisible({ timeout: 500 })) {
        await selectionItem.click();
      } else {
        await selector.click();
      }
    } catch {
      await selector.click({ force: true });
    }

    const memberOption = page
      .locator('.ant-select-dropdown:visible .ant-select-item-option-content')
      .filter({ hasText: memberDisplayName })
      .first();
    await expect(memberOption).toBeVisible({ timeout: 10000 });
    await memberOption.click();
  }

  await page.reload();

  // Verify selection shown in header updated
  const headerSelection = page.locator('header').locator('.ant-select-selection-item').first();
  await expect(headerSelection).toBeVisible({ timeout: 10000 });
  await expect(headerSelection).toContainText(memberDisplayName, { timeout: 10000 });
  
  console.log(`Switched to member: ${memberDisplayName}`);
}
