/**
 * Session management utilities for E2E tests
 * Provides helpers to use shared authentication state or create unique users when needed
 * Generated by Copilot
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const STORAGE_STATE_PATH = path.join(__dirname, '..', '.auth', 'user.json');
const SHARED_USER_PATH = path.join(__dirname, '..', '.auth', 'shared-user.json');

/**
 * Get the shared test user data created by global setup
 * @returns {Object} Shared user data with username, email, password, etc.
 */
export function getSharedUser() {
  if (!fs.existsSync(SHARED_USER_PATH)) {
    throw new Error(
      `Shared user file not found: ${SHARED_USER_PATH}\n` +
      'Make sure global setup has run. This should happen automatically on first test run.'
    );
  }
  
  const userData = fs.readFileSync(SHARED_USER_PATH, 'utf-8');
  return JSON.parse(userData);
}

/**
 * Check if shared authentication state exists
 * @returns {boolean} True if auth state file exists
 */
export function hasSharedAuth() {
  return fs.existsSync(STORAGE_STATE_PATH);
}

/**
 * Get path to shared authentication state file
 * @returns {string} Path to storageState file
 */
export function getStorageStatePath() {
  return STORAGE_STATE_PATH;
}

/**
 * Check if test should use shared authentication
 * Can be disabled via environment variable for tests requiring unique users
 * @returns {boolean} True if shared auth should be used
 */
export function shouldUseSharedAuth() {
  // Allow tests to opt-out of shared auth via environment variable
  return process.env.E2E_NO_SHARED_AUTH !== '1';
}
