/**
 * Test data factory for E2E regression tests
 * Generates minute-stamped unique identifiers to avoid collisions
 * Generated by Copilot
 */

/**
 * Generate a unique run identifier with minute-level timestamp
 * @returns {{ prefix: string, suffix: string, runId: string }}
 * @example
 * // Returns: { prefix: '20260113-0932-demo', suffix: '4821', runId: '20260113-0932-demo-4821' }
 */
export function makeRunId() {
  const now = new Date();
  
  // Format: YYYYMMDD-HHmm-demo
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const hour = String(now.getHours()).padStart(2, '0');
  const minute = String(now.getMinutes()).padStart(2, '0');
  
  const prefix = `${year}${month}${day}-${hour}${minute}-demo`;
  
  // Generate a short suffix to avoid same-minute collisions
  const suffix = String(Math.floor(Math.random() * 10000)).padStart(4, '0');
  
  const runId = `${prefix}-${suffix}`;
  
  return { prefix, suffix, runId };
}

/**
 * Generate test user data with minute-stamped unique identifiers
 * @param {string} [runId] - Optional run ID; if not provided, generates new one
 * @returns {{ username: string, email: string, password: string, age: number, gender: string, weight: number, runId: string }}
 */
export function makeUser(runId) {
  if (!runId) {
    runId = makeRunId().runId;
  }
  
  return {
    username: runId,
    email: `e2e.${runId}@example.com`,
    password: 'TestPassword123!',
    age: 30,
    gender: 'male',
    weight: 70,
    runId,
  };
}

/**
 * Generate a timestamped family member name
 * @param {string} [runId] - Optional run ID; if not provided, generates new one
 * @returns {string} Member name with timestamp
 */
export function makeMemberName(runId) {
  if (!runId) {
    runId = makeRunId().runId;
  }
  
  return `Member-${runId}`;
}
