"""
Resilience layer using tenacity (retry) and pybreaker (circuit breaker).
Generated by Zhuang
"""
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type
import pybreaker
from sqlalchemy.exc import SQLAlchemyError


db_breaker = pybreaker.CircuitBreaker(fail_max=5, reset_timeout=30)


def with_retry(exceptions=(SQLAlchemyError,), attempts=3):
    return retry(stop=stop_after_attempt(attempts), wait=wait_exponential(multiplier=0.2, min=0.2, max=2),
                 retry=retry_if_exception_type(exceptions))
