@echo off
REM Generated by Zhuang
REM Script to extract kubectl configuration for GitHub Environment setup

echo 🔍 Extracting kubectl configuration for GitHub Environment setup
echo =================================================

REM Check if kubectl is available
kubectl version --client >nul 2>&1
if errorlevel 1 (
    echo ❌ kubectl is not installed or not in PATH
    exit /b 1
)

REM Get current context
for /f "delims=" %%i in ('kubectl config current-context 2^>nul') do set CURRENT_CONTEXT=%%i
if "%CURRENT_CONTEXT%"=="" (
    echo ❌ No current kubectl context found
    echo 💡 Please configure kubectl to connect to your cluster first
    exit /b 1
)

echo ✅ Current kubectl context: %CURRENT_CONTEXT%

REM Get cluster name
for /f "delims=" %%i in ('kubectl config view --minify -o jsonpath^="{.clusters[].name}" 2^>nul') do set CLUSTER_NAME=%%i
echo ✅ Cluster name: %CLUSTER_NAME%

REM Get server URL (for verification)
for /f "delims=" %%i in ('kubectl config view --minify -o jsonpath^="{.clusters[].cluster.server}" 2^>nul') do set SERVER_URL=%%i
echo ✅ Cluster server: %SERVER_URL%

echo.
echo 📋 GitHub Environment Secrets to configure:
echo =================================================

echo.
echo 🔑 KUBE_CONTEXT:
echo %CURRENT_CONTEXT%

echo.
echo 🔑 KUBE_CONFIG:
echo Copy the entire raw YAML output below:
echo ---

REM Get a single-context raw kubeconfig
kubectl config view --minify --raw 2>nul

echo ---

echo.
echo 💡 Instructions:
echo 1. Go to GitHub → Repository → Settings → Environments
echo 2. Select your environment (staging/production)
echo 3. Add the following secrets:
echo    - KUBE_CONFIG: [copy the raw YAML above without Base64 encoding]
echo    - GHCR_READ_TOKEN: [token with read:packages only]
echo 4. Add the following variable:
echo    - GHCR_USERNAME: GitHub login that owns GHCR_READ_TOKEN

echo.
echo ✅ Configuration extraction complete!
