"""
Minimal smoke test to ensure app can create and healthz works. Generated by Zhuang
"""
from src.app import create_app


def main():
    app = create_app()
    client = app.test_client()
    r = client.get("/api/healthz")
    assert r.status_code == 200
    print("healthz:", r.json)


if __name__ == "__main__":
    main()
