"""
Entry point for the Health Platform backend API. Generated by Zhuang
"""
from flask import Flask, jsonify
from flask.cli import with_appcontext  # Generated by Zhuang
import os  # Generated by Zhuang
from sqlalchemy.engine import make_url  # Generated by Zhuang
from sqlalchemy import text, inspect  # Generated by Zhuang
from .config import Config
from .extensions import db, jwt, limiter, cors, migrate
from .service.auth_service import auth_bp
from .service.user_service import user_bp
from .service.health_service import health_bp
from .service.health_import_service import health_import_bp
from .service.member_service import member_bp
from .service.admin_service import admin_bp
from .service.version_service import version_bp
from .service.medical_history_service import medical_history_bp
from .errors import register_error_handlers
from flask import request, jsonify
from flask_jwt_extended import verify_jwt_in_request, get_jwt_identity
from .utils import error
from .manager.user_manager import UserManager


def create_app(config_class: type = Config) -> Flask:
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Generated by Zhuang: ensure SQLite path is absolute and directory exists
    try:
        uri = app.config.get("SQLALCHEMY_DATABASE_URI")
        if uri:
            url = make_url(uri)
            if url.get_backend_name() == "sqlite":
                db_path = url.database
                if db_path and db_path != ":memory:":
                    # if relative, resolve against project root (app.root_path)
                    if not os.path.isabs(db_path):
                        abs_path = os.path.normpath(os.path.join(app.root_path, db_path))
                    else:
                        abs_path = db_path
                    os.makedirs(os.path.dirname(abs_path), exist_ok=True)
                    # rebuild absolute file URI (use forward slashes on Windows)
                    abs_uri = "sqlite:///" + abs_path.replace("\\", "/")
                    app.config["SQLALCHEMY_DATABASE_URI"] = abs_uri
    except Exception:
        # Non-fatal safeguard; continue initialization
        pass

    # MySQL engine robustness + optional TLS. Generated by Zhuang
    try:
        uri_eff = app.config.get("SQLALCHEMY_DATABASE_URI")
        if uri_eff:
            url_eff = make_url(uri_eff)
            if url_eff.get_backend_name() in ("mysql", "mariadb"):
                eng_opts = dict(app.config.get("SQLALCHEMY_ENGINE_OPTIONS", {}))
                # Avoid stale connections and NAT timeouts
                eng_opts.setdefault("pool_pre_ping", True)
                eng_opts.setdefault("pool_recycle", int(os.getenv("DB_POOL_RECYCLE", "280")))
                # Optional TLS for Azure MySQL. MYSQL_SSL=1 to enable; MYSQL_SSL_CA to specify CA file
                if os.getenv("MYSQL_SSL", "").lower() in ("1", "true", "yes"):
                    ca = os.getenv("MYSQL_SSL_CA")
                    if ca:
                        eng_opts.setdefault("connect_args", {}).setdefault("ssl", {"ca": ca})
                    else:
                        # Enable TLS without custom CA (server-provided); not verifying CA strictly
                        eng_opts.setdefault("connect_args", {}).setdefault("ssl", {})
                app.config["SQLALCHEMY_ENGINE_OPTIONS"] = eng_opts
    except Exception:
        pass

    # Init extensions
    db.init_app(app)
    jwt.init_app(app)
    limiter.init_app(app)
    migrate.init_app(app, db)
    # Generated by Zhuang: CORS relaxed for local dev and export download
    cors.init_app(app, resources={
        r"/api/*": {
            "origins": app.config.get("CORS_ORIGINS"),
            # Allow common headers incl. lowercase 'authorization' to satisfy some browsers' preflight
            "allow_headers": [
                "Authorization",
                "authorization",
                "Content-Type",
                "X-Requested-With"
            ],
            # Expose filename for CSV download
            "expose_headers": ["Content-Disposition"],
            # Explicitly allow OPTIONS for preflight
            "methods": ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
            # Allow credentials if the client opts in (cookies/authorization)
            "supports_credentials": True,
        }
    })

    with app.app_context():
        # Generated by Zhuang: Avoid startup hang if external DB is unreachable.
        # Create tables automatically in safe scenarios:
        # - Always for SQLite (dev convenience)
        # - For external DBs (e.g., MySQL) when key tables are missing, or when DB_AUTO_CREATE=1
        # Can be disabled with DB_AUTO_CREATE=0 or DB_CREATE_ON_MISSING=0
        try:
            uri = app.config.get("SQLALCHEMY_DATABASE_URI")
            backend = make_url(uri).get_backend_name() if uri else None
            # Best-effort connectivity probe first
            try:
                db.session.execute(text("SELECT 1"))
            except Exception:
                pass

            should_create = False
            if backend == "sqlite":
                should_create = True
            else:
                # External DBs: allow opt-in via env, or auto if required app tables are missing
                auto_env = os.getenv("DB_AUTO_CREATE", "").lower() in ("1", "true", "yes")
                on_missing_env = os.getenv("DB_CREATE_ON_MISSING", "1").lower() in ("1", "true", "yes")
                if auto_env:
                    should_create = True
                elif on_missing_env:
                    try:
                        insp = inspect(db.engine)
                        existing = set(insp.get_table_names())
                        required = {"users", "members", "health_records", "households", "record_subjects"}
                        if not required.issubset(existing):
                            should_create = True
                    except Exception:
                        # If inspection fails, do not block startup; skip create to be safe
                        pass

            if should_create:
                try:
                    db.create_all()
                except Exception:
                    # Do not crash the app due to DDL issues; surface via logs and continue
                    pass
            # Best-effort: ensure new columns exist on existing DBs to avoid runtime 500s
            try:
                insp2 = inspect(db.engine)
                table_names = set(insp2.get_table_names())
                conn = db.session.connection()
                if 'users' in table_names:
                    cols = {c['name'] for c in insp2.get_columns('users')}
                    # Add role column
                    if 'role' not in cols:
                        try:
                            conn.execute(text("ALTER TABLE users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER'"))
                        except Exception:
                            pass
                    # Add must_change_password column
                    if 'must_change_password' not in cols:
                        try:
                            # Use INTEGER 0/1 for broad compatibility
                            conn.execute(text("ALTER TABLE users ADD COLUMN must_change_password INTEGER NOT NULL DEFAULT 0"))
                        except Exception:
                            pass
                    # Add last_login_at column
                    if 'last_login_at' not in cols:
                        try:
                            conn.execute(text("ALTER TABLE users ADD COLUMN last_login_at DATETIME NULL"))
                        except Exception:
                            pass

                # Backfill Phase 1 guest-trial columns on existing DBs.
                guest_trial_column_specs = {
                    'health_records': "ALTER TABLE health_records ADD COLUMN guest_trial_session_id VARCHAR(64) NULL",
                    'households': "ALTER TABLE households ADD COLUMN guest_trial_session_id VARCHAR(64) NULL",
                    'members': "ALTER TABLE members ADD COLUMN guest_trial_session_id VARCHAR(64) NULL",
                    'record_subjects': "ALTER TABLE record_subjects ADD COLUMN guest_trial_session_id VARCHAR(64) NULL",
                }
                for table_name, ddl in guest_trial_column_specs.items():
                    if table_name not in table_names:
                        continue
                    cols = {c['name'] for c in insp2.get_columns(table_name)}
                    if 'guest_trial_session_id' in cols:
                        continue
                    try:
                        conn.execute(text(ddl))
                    except Exception:
                        pass
                        
            except Exception:
                pass
            # Ensure default SUPER_ADMIN account exists (skip in tests)
            if not app.config.get("TESTING", False):
                try:
                    from .manager.user_manager import UserManager
                    from .models import User
                    um = UserManager()
                    # Default credentials configurable via env
                    sa_email = os.getenv("SUPER_ADMIN_EMAIL", "admin@example.com")
                    sa_username = (os.getenv("SUPER_ADMIN_USERNAME", "Super_Admin") or "Super_Admin")
                    sa_password = os.getenv("SUPER_ADMIN_PASSWORD", "ChangeMe123")
                    existing = User.query.filter_by(email=sa_email).first()
                    if not existing:
                        sa = um.create_user(username=sa_username, email=sa_email, password=sa_password)
                        um.set_role(sa, "SUPER_ADMIN")
                        # Force password change on first login
                        sa.must_change_password = True
                        db.session.commit()
                    else:
                        # Ensure role is SUPER_ADMIN (do not downgrade silently)
                        if existing.role != "SUPER_ADMIN":
                            existing.role = "SUPER_ADMIN"
                            db.session.commit()
                except Exception:
                    # Non-fatal: do not block app startup
                    pass
        except Exception:
            pass

    # Register blueprints (service layer)
    app.register_blueprint(auth_bp, url_prefix="/api/v1/auth")
    app.register_blueprint(user_bp, url_prefix="/api/v1/user")
    app.register_blueprint(health_bp, url_prefix="/api/v1/health")
    app.register_blueprint(health_import_bp, url_prefix="/api/v1/health/import")
    app.register_blueprint(member_bp, url_prefix="/api/v1/members")
    app.register_blueprint(admin_bp, url_prefix="/api/v1/admin")
    app.register_blueprint(version_bp, url_prefix="/api/v1/version")
    app.register_blueprint(medical_history_bp, url_prefix="/api/v1/medical-history")

    # Generated by Zhuang: lightweight anonymous health endpoint for k8s probes
    @app.get("/api/healthz")
    def healthz():  # pragma: no cover - trivial
        return jsonify({"status": "ok"}), 200

    # Errors
    register_error_handlers(app)

    # Removed duplicate /healthz (prefer /api/healthz for probes). Generated by Zhuang

    # Generated by Zhuang: CLI - db-info
    @app.cli.command("db-info")
    def db_info():
        """Print DB dialect, server/client encodings, and table list. Generated by Zhuang"""
        eng = db.engine
        insp = inspect(eng)
        print("URL      :", eng.url)
        print("Dialect  :", eng.dialect.name)
        # server encoding / collation best effort
        server_info = None
        try:
            if eng.dialect.name == "sqlite":
                server_info = db.session.execute(text("PRAGMA encoding")).scalar()
            elif eng.dialect.name == "mysql":
                cs = db.session.execute(text("SHOW VARIABLES LIKE 'character_set_database'"))
                coll = db.session.execute(text("SHOW VARIABLES LIKE 'collation_database'"))
                cs_map = {k: v for k, v in cs}
                coll_map = {k: v for k, v in coll}
                server_info = f"{cs_map.get('character_set_database')}, {coll_map.get('collation_database')}"
            elif eng.dialect.name in ("mssql", "pyodbc"):
                server_info = db.session.execute(text("SELECT CONVERT(sysname, DATABASEPROPERTYEX(DB_NAME(), 'Collation'))")).scalar()
        except Exception as e:
            server_info = f"n/a ({e})"
        print("Encoding :", getattr(eng.dialect, 'encoding', 'utf-8'))
        print("Server   :", server_info or "n/a")
        tables = insp.get_table_names()
        print("Tables   :", ", ".join(tables) if tables else "(none)")

    # Generated by Zhuang: CLI - db-create (create all tables explicitly for non-SQLite DBs)
    @app.cli.command("db-create")
    @with_appcontext
    def db_create():
        """Create all database tables using SQLAlchemy metadata. Generated by Zhuang"""
        db.create_all()
        insp = inspect(db.engine)
        tables = insp.get_table_names()
        print(f"Created tables: {', '.join(tables) if tables else '(none)'}")

    # Generated by Zhuang: avoid proxy noise in dev when browser requests /favicon.ico
    @app.route("/favicon.ico")
    def favicon():
        return "", 204

    @app.route("/favicon.svg")
    def favicon_svg():
        return "", 204

    # Enforce must_change_password for authenticated requests except whitelisted endpoints
    @app.before_request
    def enforce_password_change_middleware():  # pragma: no cover (validated via endpoint tests)
        try:
            # Skip non-API paths
            p = request.path or ""
            if not p.startswith("/api/"):
                return None
            # Whitelist endpoints that should work before changing password
            whitelist = {
                "/api/healthz",
                "/api/v1/auth/change-password",
                "/api/v1/auth/refresh",
                "/api/v1/auth/logout",
                "/api/v1/auth/logout-all",
                "/api/v1/version",
            }
            if p in whitelist:
                return None
            # If request has a JWT, check flag from DB for accuracy
            verify_jwt_in_request(optional=True)
            identity = get_jwt_identity()
            if not identity:
                return None
            um = UserManager()
            user = um.get_user(identity)
            if user and user.must_change_password:
                return jsonify(error("403", "Must change password before accessing other features")), 403
        except Exception:
            # Fail-open on middleware errors to avoid breaking APIs unexpectedly
            return None

    return app
