"""
Unified error handlers. Generated by Zhuang
"""
from flask import jsonify
from werkzeug.exceptions import HTTPException
from .utils import error


def register_error_handlers(app):
    @app.errorhandler(HTTPException)
    def handle_http_exception(e: HTTPException):
        body = error(code=str(e.code), message=e.name, details=e.description)
        return jsonify(body), e.code

    @app.errorhandler(Exception)
    def handle_exception(e: Exception):
        app.logger.exception("Unhandled application error", exc_info=e)
        body = error(code="500", message="Internal Server Error")
        return jsonify(body), 500
