"""
SQLAlchemy models. Generated by Zhuang
"""
from datetime import datetime
from .timeutil import UTC
from typing import Optional
from .extensions import db


# Generated by Zhuang: Begin Family (Household/Member) simplified models (non-breaking)
class Household(db.Model):
    __tablename__ = "households"
    id = db.Column(db.Integer, primary_key=True)
    owner_user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    name = db.Column(db.String(120), nullable=False)
    # Use naive UTC for MySQL compatibility
    # Use timezone-aware UTC to avoid deprecation warnings in Python 3.12+
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(UTC), nullable=False)


class Member(db.Model):
    __tablename__ = "members"
    id = db.Column(db.Integer, primary_key=True)
    household_id = db.Column(db.Integer, db.ForeignKey("households.id"), nullable=False)
    full_name = db.Column(db.String(120), nullable=False)
    gender = db.Column(db.String(16))  # male/female/other
    age = db.Column(db.Integer)
    height = db.Column(db.Float)
    weight = db.Column(db.Float)
    status = db.Column(db.String(16), default="active", nullable=False)  # active/inactive
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(UTC), nullable=False)


class RecordSubject(db.Model):
    __tablename__ = "record_subjects"
    id = db.Column(db.Integer, primary_key=True)
    record_id = db.Column(db.Integer, db.ForeignKey("health_records.id"), nullable=False, index=True)
    household_id = db.Column(db.Integer, db.ForeignKey("households.id"), nullable=False)
    member_id = db.Column(db.Integer, db.ForeignKey("members.id"), nullable=False, index=True)
    created_by_user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(UTC), nullable=False)
# Generated by Zhuang: End Family models


class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    # Role-based access: USER, ADMIN, SUPER_ADMIN
    role = db.Column(db.String(20), default="USER", nullable=False)
    # Force password change on next login (e.g., admin reset or default super admin)
    must_change_password = db.Column(db.Boolean, default=False, nullable=False)
    age = db.Column(db.Integer)
    gender = db.Column(db.String(16))
    weight = db.Column(db.Float)
    token_version = db.Column(db.Integer, default=0, nullable=False)
    # Track last successful login for admin visibility
    last_login_at = db.Column(db.DateTime)
    # Store timezone-aware UTC datetimes; ensure consistent serialization
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(UTC), nullable=False)
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC), nullable=False)

    records = db.relationship("HealthRecord", backref="user", lazy=True)


class HealthRecord(db.Model):
    __tablename__ = "health_records"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    systolic = db.Column(db.Integer, nullable=False)
    diastolic = db.Column(db.Integer, nullable=False)
    heart_rate = db.Column(db.Integer, nullable=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    tags = db.Column(db.Text)  # store as JSON string
    note = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(UTC), nullable=False)


class HealthImportSession(db.Model):
    __tablename__ = "health_import_sessions"

    # Use string UUID for session id to make it easy to return to clients
    id = db.Column(db.String(64), primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False, index=True)
    original_filename = db.Column(db.String(255))
    file_size_bytes = db.Column(db.Integer)
    file_sha256 = db.Column(db.String(128))
    mapping_json = db.Column(db.Text)
    normalized_rows_json = db.Column(db.Text)
    preview_errors_json = db.Column(db.Text)
    preview_skipped_json = db.Column(db.Text)
    unknown_members_json = db.Column(db.Text)
    status = db.Column(db.String(32), default="previewed", nullable=False)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(UTC), nullable=False)
    expires_at = db.Column(db.DateTime)


class HealthImportAudit(db.Model):
    __tablename__ = "health_import_audits"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False, index=True)
    session_id = db.Column(db.String(64))
    original_filename = db.Column(db.String(255))
    file_size_bytes = db.Column(db.Integer)
    file_sha256 = db.Column(db.String(128))
    total_rows = db.Column(db.Integer)
    success_count = db.Column(db.Integer)
    error_count = db.Column(db.Integer)
    skipped_count = db.Column(db.Integer)
    created_members_count = db.Column(db.Integer)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(UTC), nullable=False)
